trigger:
  branches:
    include:
      - main

variables:
  - group: Secrets

pool:
  vmImage: ubuntu-latest

steps:
  - task: Checkout@1

  - script: |
      echo "🎉 Starting deployment"
      git config user.email "you@example.com"
      git config user.name "Your Name"
      git checkout gh-pages || git checkout --orphan gh-pages
      git rm -rf .
      cp -r * .  # copie des fichiers vers la racine
      git add .
      git commit -m "Deploy from Azure Pipelines"
      git push https://${GH_TOKEN}@github.com/abdelwaheb-net/Word-Counter.git gh-pages --force
    displayName: '🚀 Deploy to GitHub Pages'
    env:
      GH_TOKEN: $(GH_TOKEN)
