trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

# Étape de build éventuelle ici si tu as du build à faire (ex: React, Vue, etc.)

- script: |
    git config user.email "you@example.com"
    git config user.name "Your Name"
    git fetch
    git checkout gh-pages || git checkout --orphan gh-pages
    git rm -rf .
    cp -r path-to-your-site/* .
    git add .
    git commit -m "Deploy from Azure Pipelines"
    git push origin gh-pages --force
  displayName: 'Deploy to GitHub Pages'
