name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install gh-pages --save-dev

      - name: Deploy with gh-pages
        run: |
          npx gh-pages -d . -b gh-pages
